### ISSUE TITLE
Bill-to and Payment Method Not Being Set For Invoices

### ISSUE THREAD

**Issue by performadigital** [pmclain/module-stripe#39] opened 2018-04-06 11:32 UTC
Hi there,

We're having a bit of a strange issue where when using the Stripe payment method on our Magento 2.1.11 site the Bill-to and Payment Method fields are not being populated. When testing this with other payment methods the data is set correctly.

This occurs not only on the Invoice admin grid but also when viewing the individual invoice. The billing address does appear to be set.

These orders are for virtual products which might be causing part of the issue?

Also to note in our test environment our admin users are using the en_US locale with the frontend being en_GB, which possibly could cause currency issues but that shouldn't be an issue I'd of thought.

Any ideas?

![image](https://user-images.githubusercontent.com/7970038/38419160-42c5b1ae-3997-11e8-8525-02ff130c3cab.png)

**Comment by performadigital** [comment] 2018-04-06 12:27
I'm currently using the commit prior to that branch being merged in the past 24 hours. This is due to a small fix I made to the pmclain_stripe.js when region isn't set (cannot be null). I'll fork and create a PR for that if you think it's worthwhile?

**Comment by pmclain** [comment] 2018-04-06 12:29
Yes, please do.

**Comment by pmclain** [comment] 2018-04-06 12:54
I was able to reproduce the missing bill-to on a clean version of 2.1.11. The payment method name appears. I suspect that's because I added a config default for method title in v1.2.0, because the method name displayed is the default and not the value I have configured in the admin.

**Comment by performadigital** [comment] 2018-04-06 13:02
Interestingly, we actually do have the Payment Method being set correctly (still missing Bill-to) on our development site, our live site however is missing the data from this field.

![image](https://user-images.githubusercontent.com/7970038/38422561-1eec803a-39a3-11e8-8290-ebadd302ca1e.png)

**Comment by pmclain** [comment] 2018-04-07 18:08
This is a core bug in Magento 2.0.x and 2.1.x with the Gateway Sale Command magento/magento2/issues/9309, magento/magento2/issues/6438. It was fixed in core starting with 2.2.0, https://github.com/magento/magento2/commit/a2762416af2341d61c37b0b57203c891ae649d70

It looks like the fix was an [after plugin](https://github.com/magento/magento2/commit/a2762416af2341d61c37b0b57203c891ae649d70#diff-2e4424867f82a1c6b83d62d531fedcc9) on `Magento\Sales\Model\ResourceModel\Order\Handler\Address::process`.

**Closed by pmclain** 2018-04-07 18:08 UTC
Labels: bug, in progress

**Comment by performadigital** [comment] 2018-04-11 09:14
Wonderful thanks for taking the time to look into this as I'd got a bit lost in the mass of issue reports and apparent fixes over on the Mage repo!
